// Code generated by MockGen. DO NOT EDIT.
// Source: root.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "github.com/EshkinKot1980/GophKeeper/internal/common/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockPrompt is a mock of Prompt interface.
type MockPrompt struct {
	ctrl     *gomock.Controller
	recorder *MockPromptMockRecorder
}

// MockPromptMockRecorder is the mock recorder for MockPrompt.
type MockPromptMockRecorder struct {
	mock *MockPrompt
}

// NewMockPrompt creates a new mock instance.
func NewMockPrompt(ctrl *gomock.Controller) *MockPrompt {
	mock := &MockPrompt{ctrl: ctrl}
	mock.recorder = &MockPromptMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrompt) EXPECT() *MockPromptMockRecorder {
	return m.recorder
}

// Credentials mocks base method.
func (m *MockPrompt) Credentials() (dto.Credentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Credentials")
	ret0, _ := ret[0].(dto.Credentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Credentials indicates an expected call of Credentials.
func (mr *MockPromptMockRecorder) Credentials() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Credentials", reflect.TypeOf((*MockPrompt)(nil).Credentials))
}

// Overwrite mocks base method.
func (m *MockPrompt) Overwrite(fileName string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Overwrite", fileName)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Overwrite indicates an expected call of Overwrite.
func (mr *MockPromptMockRecorder) Overwrite(fileName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Overwrite", reflect.TypeOf((*MockPrompt)(nil).Overwrite), fileName)
}

// RegisterCredentials mocks base method.
func (m *MockPrompt) RegisterCredentials() (dto.Credentials, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterCredentials")
	ret0, _ := ret[0].(dto.Credentials)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterCredentials indicates an expected call of RegisterCredentials.
func (mr *MockPromptMockRecorder) RegisterCredentials() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterCredentials", reflect.TypeOf((*MockPrompt)(nil).RegisterCredentials))
}

// SecretName mocks base method.
func (m *MockPrompt) SecretName() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SecretName")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SecretName indicates an expected call of SecretName.
func (mr *MockPromptMockRecorder) SecretName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SecretName", reflect.TypeOf((*MockPrompt)(nil).SecretName))
}

// Text mocks base method.
func (m *MockPrompt) Text() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Text")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Text indicates an expected call of Text.
func (mr *MockPromptMockRecorder) Text() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Text", reflect.TypeOf((*MockPrompt)(nil).Text))
}
