// Code generated by MockGen. DO NOT EDIT.
// Source: root.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "github.com/EshkinKot1980/GophKeeper/internal/common/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockSecretService is a mock of SecretService interface.
type MockSecretService struct {
	ctrl     *gomock.Controller
	recorder *MockSecretServiceMockRecorder
}

// MockSecretServiceMockRecorder is the mock recorder for MockSecretService.
type MockSecretServiceMockRecorder struct {
	mock *MockSecretService
}

// NewMockSecretService creates a new mock instance.
func NewMockSecretService(ctrl *gomock.Controller) *MockSecretService {
	mock := &MockSecretService{ctrl: ctrl}
	mock.recorder = &MockSecretServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretService) EXPECT() *MockSecretServiceMockRecorder {
	return m.recorder
}

// GetSecretAndInfo mocks base method.
func (m *MockSecretService) GetSecretAndInfo(id uint64) ([]byte, dto.SecretInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSecretAndInfo", id)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(dto.SecretInfo)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSecretAndInfo indicates an expected call of GetSecretAndInfo.
func (mr *MockSecretServiceMockRecorder) GetSecretAndInfo(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSecretAndInfo", reflect.TypeOf((*MockSecretService)(nil).GetSecretAndInfo), id)
}

// InfoList mocks base method.
func (m *MockSecretService) InfoList() ([]dto.SecretInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InfoList")
	ret0, _ := ret[0].([]dto.SecretInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InfoList indicates an expected call of InfoList.
func (mr *MockSecretServiceMockRecorder) InfoList() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfoList", reflect.TypeOf((*MockSecretService)(nil).InfoList))
}

// Upload mocks base method.
func (m *MockSecretService) Upload(secret dto.SecretRequest, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", secret, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *MockSecretServiceMockRecorder) Upload(secret, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockSecretService)(nil).Upload), secret, data)
}
