// Code generated by MockGen. DO NOT EDIT.
// Source: secret.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/EshkinKot1980/GophKeeper/internal/server/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockSecretRepository is a mock of SecretRepository interface.
type MockSecretRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSecretRepositoryMockRecorder
}

// MockSecretRepositoryMockRecorder is the mock recorder for MockSecretRepository.
type MockSecretRepositoryMockRecorder struct {
	mock *MockSecretRepository
}

// NewMockSecretRepository creates a new mock instance.
func NewMockSecretRepository(ctrl *gomock.Controller) *MockSecretRepository {
	mock := &MockSecretRepository{ctrl: ctrl}
	mock.recorder = &MockSecretRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretRepository) EXPECT() *MockSecretRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSecretRepository) Create(ctx context.Context, secret entity.Secret) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, secret)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSecretRepositoryMockRecorder) Create(ctx, secret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSecretRepository)(nil).Create), ctx, secret)
}

// GetAllUnencryptedByUser mocks base method.
func (m *MockSecretRepository) GetAllUnencryptedByUser(ctx context.Context, userID string) ([]entity.SecretInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUnencryptedByUser", ctx, userID)
	ret0, _ := ret[0].([]entity.SecretInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUnencryptedByUser indicates an expected call of GetAllUnencryptedByUser.
func (mr *MockSecretRepositoryMockRecorder) GetAllUnencryptedByUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUnencryptedByUser", reflect.TypeOf((*MockSecretRepository)(nil).GetAllUnencryptedByUser), ctx, userID)
}

// GetForUser mocks base method.
func (m *MockSecretRepository) GetForUser(ctx context.Context, secretID uint64, userID string) (entity.Secret, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForUser", ctx, secretID, userID)
	ret0, _ := ret[0].(entity.Secret)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForUser indicates an expected call of GetForUser.
func (mr *MockSecretRepositoryMockRecorder) GetForUser(ctx, secretID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForUser", reflect.TypeOf((*MockSecretRepository)(nil).GetForUser), ctx, secretID, userID)
}
