// Code generated by MockGen. DO NOT EDIT.
// Source: secret.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/EshkinKot1980/GophKeeper/internal/common/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockSecretService is a mock of SecretService interface.
type MockSecretService struct {
	ctrl     *gomock.Controller
	recorder *MockSecretServiceMockRecorder
}

// MockSecretServiceMockRecorder is the mock recorder for MockSecretService.
type MockSecretServiceMockRecorder struct {
	mock *MockSecretService
}

// NewMockSecretService creates a new mock instance.
func NewMockSecretService(ctrl *gomock.Controller) *MockSecretService {
	mock := &MockSecretService{ctrl: ctrl}
	mock.recorder = &MockSecretServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSecretService) EXPECT() *MockSecretServiceMockRecorder {
	return m.recorder
}

// InfoList mocks base method.
func (m *MockSecretService) InfoList(ctx context.Context) ([]dto.SecretInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InfoList", ctx)
	ret0, _ := ret[0].([]dto.SecretInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InfoList indicates an expected call of InfoList.
func (mr *MockSecretServiceMockRecorder) InfoList(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfoList", reflect.TypeOf((*MockSecretService)(nil).InfoList), ctx)
}

// Save mocks base method.
func (m *MockSecretService) Save(ctx context.Context, secret *dto.SecretRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, secret)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockSecretServiceMockRecorder) Save(ctx, secret interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockSecretService)(nil).Save), ctx, secret)
}

// Secret mocks base method.
func (m *MockSecretService) Secret(ctx context.Context, secretID uint64) (dto.SecretResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Secret", ctx, secretID)
	ret0, _ := ret[0].(dto.SecretResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Secret indicates an expected call of Secret.
func (mr *MockSecretServiceMockRecorder) Secret(ctx, secretID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Secret", reflect.TypeOf((*MockSecretService)(nil).Secret), ctx, secretID)
}
