// Code generated by MockGen. DO NOT EDIT.
// Source: secret.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	dto "github.com/EshkinKot1980/GophKeeper/internal/common/dto"
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// InfoList mocks base method.
func (m *MockClient) InfoList(token string) ([]dto.SecretInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InfoList", token)
	ret0, _ := ret[0].([]dto.SecretInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InfoList indicates an expected call of InfoList.
func (mr *MockClientMockRecorder) InfoList(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InfoList", reflect.TypeOf((*MockClient)(nil).InfoList), token)
}

// Login mocks base method.
func (m *MockClient) Login(cr dto.Credentials) (dto.AuthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", cr)
	ret0, _ := ret[0].(dto.AuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockClientMockRecorder) Login(cr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockClient)(nil).Login), cr)
}

// Register mocks base method.
func (m *MockClient) Register(cr dto.Credentials) (dto.AuthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", cr)
	ret0, _ := ret[0].(dto.AuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockClientMockRecorder) Register(cr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockClient)(nil).Register), cr)
}

// Retrieve mocks base method.
func (m *MockClient) Retrieve(id uint64, token string) (dto.SecretResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Retrieve", id, token)
	ret0, _ := ret[0].(dto.SecretResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Retrieve indicates an expected call of Retrieve.
func (mr *MockClientMockRecorder) Retrieve(id, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Retrieve", reflect.TypeOf((*MockClient)(nil).Retrieve), id, token)
}

// Upload mocks base method.
func (m *MockClient) Upload(data dto.SecretRequest, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", data, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *MockClientMockRecorder) Upload(data, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockClient)(nil).Upload), data, token)
}
