// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// Key mocks base method.
func (m *MockStorage) Key() ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Key")
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Key indicates an expected call of Key.
func (mr *MockStorageMockRecorder) Key() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Key", reflect.TypeOf((*MockStorage)(nil).Key))
}

// PutKey mocks base method.
func (m *MockStorage) PutKey(key []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutKey", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutKey indicates an expected call of PutKey.
func (mr *MockStorageMockRecorder) PutKey(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutKey", reflect.TypeOf((*MockStorage)(nil).PutKey), key)
}

// PutToken mocks base method.
func (m *MockStorage) PutToken(token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutToken", token)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutToken indicates an expected call of PutToken.
func (mr *MockStorageMockRecorder) PutToken(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutToken", reflect.TypeOf((*MockStorage)(nil).PutToken), token)
}

// Token mocks base method.
func (m *MockStorage) Token() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Token")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Token indicates an expected call of Token.
func (mr *MockStorageMockRecorder) Token() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Token", reflect.TypeOf((*MockStorage)(nil).Token))
}
